wip argocd create project
Signed-off-by: Rocio Philipps <rocio.philippsvalencia@mcn.gouv.qc.ca>

diff --git a/actions/create-argocd-app/action.yml b/actions/create-argocd-app/action.yml
--- a/actions/create-argocd-app/action.yml
+++ b/actions/create-argocd-app/action.yml
@@ -95,18 +95,22 @@ runs:
 
     - name: Check si le projet Argo CD existe
       id: check_project
+      continue-on-error: true # This ensures the step won't fail the workflow if the command errors
       shell: bash
       run: |
-        if argocd proj get ${{ inputs.app-name }}; then
-          echo "project_exists=true" >> $GITHUB_OUTPUT
-        else
-          echo "project_exists=false" >> $GITHUB_OUTPUT
-        fi
-      continue-on-error: true
+        # if argocd proj get ${{ inputs.app-name }}; then
+        #   echo "project_exists=true" >> $GITHUB_OUTPUT
+        # else
+        #   echo "project_exists=false" >> $GITHUB_OUTPUT
+        # fi
+        # Attempt to get the project and capture the exit code
+        argocd proj get ${{ inputs.app-name }} &> /dev/null
+        echo "exit_code=$?" >> $GITHUB_OUTPUT        
       
     - name: Create Argo CD project if it doesn't exist
       shell: bash
-      if: steps.check_project.outputs.project_exists == 'false'        
+      #if: steps.check_project.outputs.project_exists == 'false'        
+      if: steps.check_project.outputs.exit_code == '1' #project doesn't exist
       run: argocd app create ${{ inputs.app-name }} \
           --repo ${{ inputs.app_manifest_repo }} \
           --revision ${{ inputs.app_manifest_repo_branch }}
